name: Docker Build
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: michaelmass/actions/dagger@master
        with:
          source: ci/build-docker.ts
          infisical-token: ${{ secrets.INFISICAL_TOKEN }}
          infisical-workspace-id: ${{ secrets.INFISICAL_WORKSPACE_ID }}
